import fs from "fs";
import path from "path";
import PDFDocument from "pdfkit";

function sectionTitle(doc, text) {
  doc.moveDown(0.6);
  doc.fontSize(13).fillColor("#111").text(text, { underline: true });
  doc.moveDown(0.25);
}

function kv(doc, k, v) {
  doc.fontSize(10).fillColor("#333").text(`${k}: `, { continued: true, width: 120 });
  doc.fillColor("#000").text(v || "-", { width: 420 });
}

function bulletList(doc, title, items = []) {
  if (!items?.length) return;
  doc.fontSize(10).fillColor("#333").text(title);
  doc.moveDown(0.2);
  doc.fillColor("#000");
  items.forEach((it) => doc.text(`• ${it}`));
  doc.moveDown(0.2);
}

function scoreLine(doc, label, score, extra = "") {
  const s = score === undefined || score === null ? "-" : String(score);
  doc.fontSize(10).fillColor("#000").text(`${label}: ${s} ${extra}`);
}

export function ensureDir(p) {
  fs.mkdirSync(p, { recursive: true });
}

export function buildReportPdf({
  outDir,
  jobId,
  candidate = {},
  jobTitle,
  cv,
  project,
  summary,
}) {
  ensureDir(outDir);
  const outPath = path.join(outDir, `report_${jobId}.pdf`);
  const doc = new PDFDocument({ size: "A4", margin: 48 });

  doc.pipe(fs.createWriteStream(outPath));

  // Header
  doc.fontSize(18).fillColor("#000").text("Candidate Evaluation Report", { align: "left" });
  doc.moveDown(0.2);
  doc.fontSize(10).fillColor("#666").text(`Job ID: ${jobId}`, { align: "left" });
  doc.fontSize(10).fillColor("#666").text(`Generated at: ${new Date().toLocaleString()}`);
  doc.moveDown(0.6);

  // Candidate / Job meta
//   sectionTitle(doc, "Candidate & Role");
//   kv(doc, "Full Name", candidate.name || "-");
//   kv(doc, "Email", candidate.email || "-");
//   kv(doc, "Applied Role", jobTitle || "-");

  // CV Section
  sectionTitle(doc, "CV Match");
  scoreLine(doc, "CV Match Rate (0–0.20)", cv?.decimal);
  doc.moveDown(0.2);
  bulletList(doc, "CV Feedback:", cv?.feedback ? [cv.feedback] : []);
  // If you want to show the 1–5 weighted detail too:
  if (cv?.detail) {
    doc.fontSize(10).fillColor("#333").text("Weighted Components (1–5):");
    [
      ["Technical Match", cv.detail.technical_match],
      ["Experience Level", cv.detail.experience_level],
      ["Achievements", cv.detail.achievements],
      ["Cultural Fit", cv.detail.cultural_fit],
    ].forEach(([label, val]) => scoreLine(doc, `  - ${label}`, val));
  }

  // Project Section
  sectionTitle(doc, "Project Score");
  scoreLine(doc, "Project Score (1–5)", project?.score);
  doc.moveDown(0.2);
  bulletList(doc, "Project Feedback:", project?.feedback ? [project.feedback] : []);
  if (project?.detail) {
    doc.fontSize(10).fillColor("#333").text("Weighted Components (1–5):");
    [
      ["Correctness", project.detail.correctness],
      ["Code Quality", project.detail.code_quality],
      ["Resilience", project.detail.resilience],
      ["Documentation", project.detail.documentation],
      ["Creativity", project.detail.creativity],
    ].forEach(([label, val]) => scoreLine(doc, `  - ${label}`, val));
  }

  // Final Summary
  sectionTitle(doc, "Overall Summary");
  doc.fontSize(10).fillColor("#000").text(summary || "-", { align: "left" });

  // Footer
  doc.moveDown(0.8);
  doc.fontSize(9).fillColor("#666").text("Generated by yogadep AI CV & Project Evaluator", { align: "left" });

  doc.end();
  return outPath;
}
